// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef BUDGET_ODB_HXX
#define BUDGET_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "model/budget.hxx"

#include "auth_user-odb.hxx"
#include "family-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // budget
  //
  template <>
  struct class_traits< ::budget >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::budget >
  {
    public:
    typedef ::budget object_type;
    typedef ::budget* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // budget
  //
  template <typename A>
  struct pointer_query_columns< ::budget, id_sqlite, A >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // description
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    description_type_;

    static const description_type_ description;

    // user
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    user_type_;

    static const user_type_ user;

    // family
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    family_type_;

    static const family_type_ family;
  };

  template <typename A>
  const typename pointer_query_columns< ::budget, id_sqlite, A >::id_type_
  pointer_query_columns< ::budget, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::budget, id_sqlite, A >::amount_type_
  pointer_query_columns< ::budget, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::budget, id_sqlite, A >::description_type_
  pointer_query_columns< ::budget, id_sqlite, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::budget, id_sqlite, A >::user_type_
  pointer_query_columns< ::budget, id_sqlite, A >::
  user (A::table_name, "\"user\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::budget, id_sqlite, A >::family_type_
  pointer_query_columns< ::budget, id_sqlite, A >::
  family (A::table_name, "\"family\"", 0);

  template <>
  class access::object_traits_impl< ::budget, id_sqlite >:
    public access::object_traits< ::budget >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      // _amount
      //
      double _amount_value;
      bool _amount_null;

      // description
      //
      details::buffer description_value;
      std::size_t description_size;
      bool description_null;

      // _user
      //
      details::buffer _user_value;
      std::size_t _user_size;
      bool _user_null;

      // _family
      //
      long long _family_value;
      bool _family_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct user_tag;
    struct family_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::budget, id_common >:
    public access::object_traits_impl< ::budget, id_sqlite >
  {
  };

  // budget
  //
  template <>
  struct alias_traits<
    ::auth_user,
    id_sqlite,
    access::object_traits_impl< ::budget, id_sqlite >::user_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::family,
    id_sqlite,
    access::object_traits_impl< ::budget, id_sqlite >::family_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::budget, id_sqlite >
  {
    // user
    //
    typedef
    odb::alias_traits<
      ::auth_user,
      id_sqlite,
      access::object_traits_impl< ::budget, id_sqlite >::user_tag>
    user_alias_;

    // family
    //
    typedef
    odb::alias_traits<
      ::family,
      id_sqlite,
      access::object_traits_impl< ::budget, id_sqlite >::family_tag>
    family_alias_;
  };

  template <typename A>
  struct query_columns< ::budget, id_sqlite, A >:
    query_columns_base< ::budget, id_sqlite >
  {
    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // description
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    description_type_;

    static const description_type_ description;

    // user
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    user_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::auth_user,
        id_sqlite,
        user_alias_ > >
    user_pointer_type_;

    struct user_type_: user_pointer_type_, user_column_type_
    {
      user_type_ (const char* t, const char* c, const char* conv)
        : user_column_type_ (t, c, conv)
      {
      }
    };

    static const user_type_ user;

    // family
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    family_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::family,
        id_sqlite,
        family_alias_ > >
    family_pointer_type_;

    struct family_type_: family_pointer_type_, family_column_type_
    {
      family_type_ (const char* t, const char* c, const char* conv)
        : family_column_type_ (t, c, conv)
      {
      }
    };

    static const family_type_ family;
  };

  template <typename A>
  const typename query_columns< ::budget, id_sqlite, A >::id_type_
  query_columns< ::budget, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::budget, id_sqlite, A >::amount_type_
  query_columns< ::budget, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename query_columns< ::budget, id_sqlite, A >::description_type_
  query_columns< ::budget, id_sqlite, A >::
  description (A::table_name, "\"description\"", 0);

  template <typename A>
  const typename query_columns< ::budget, id_sqlite, A >::user_type_
  query_columns< ::budget, id_sqlite, A >::
  user (A::table_name, "\"user\"", 0);

  template <typename A>
  const typename query_columns< ::budget, id_sqlite, A >::family_type_
  query_columns< ::budget, id_sqlite, A >::
  family (A::table_name, "\"family\"", 0);
}

#include "../i/budget-odb.ixx"

#include <odb/post.hxx>

#endif // BUDGET_ODB_HXX
