// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef INCOME_ODB_HXX
#define INCOME_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "model/income.hxx"

#include "account-odb.hxx"
#include "auth_user-odb.hxx"
#include "family-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // income
  //
  template <>
  struct class_traits< ::income >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::income >
  {
    public:
    typedef ::income object_type;
    typedef ::income* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    static const bool abstract = true;
  };

  // salaried_income
  //
  template <>
  struct class_traits< ::salaried_income >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::salaried_income >
  {
    public:
    typedef ::salaried_income object_type;
    typedef ::salaried_income* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // hourly_income
  //
  template <>
  struct class_traits< ::hourly_income >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::hourly_income >
  {
    public:
    typedef ::hourly_income object_type;
    typedef ::hourly_income* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // income
  //
  template <typename A>
  struct pointer_query_columns< ::income, id_sqlite, A >
  {
    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // pay_frequency
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    pay_frequency_type_;

    static const pay_frequency_type_ pay_frequency;

    // to_acct
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    to_acct_type_;

    static const to_acct_type_ to_acct;
  };

  template <typename A>
  const typename pointer_query_columns< ::income, id_sqlite, A >::amount_type_
  pointer_query_columns< ::income, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::income, id_sqlite, A >::pay_frequency_type_
  pointer_query_columns< ::income, id_sqlite, A >::
  pay_frequency (A::table_name, "\"pay_frequency\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::income, id_sqlite, A >::to_acct_type_
  pointer_query_columns< ::income, id_sqlite, A >::
  to_acct (A::table_name, "\"to_acct\"", 0);

  template <>
  class access::object_traits_impl< ::income, id_sqlite >:
    public access::object_traits< ::income >
  {
    public:
    struct image_type
    {
      // _amount
      //
      double _amount_value;
      bool _amount_null;

      // _pay_frequency
      //
      long long _pay_frequency_value;
      bool _pay_frequency_null;

      // _to_acct
      //
      long long _to_acct_value;
      bool _to_acct_null;
    };

    struct to_acct_tag;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);
  };

  // salaried_income
  //
  template <typename A>
  struct pointer_query_columns< ::salaried_income, id_sqlite, A >:
    pointer_query_columns< ::income, id_sqlite, A >
  {
    // income
    //
    typedef pointer_query_columns< ::income, id_sqlite, A > income;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename pointer_query_columns< ::salaried_income, id_sqlite, A >::id_type_
  pointer_query_columns< ::salaried_income, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <>
  class access::object_traits_impl< ::salaried_income, id_sqlite >:
    public access::object_traits< ::salaried_income >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::income, id_sqlite >::image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 4UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::salaried_income, id_common >:
    public access::object_traits_impl< ::salaried_income, id_sqlite >
  {
  };

  // hourly_income
  //
  template <typename A>
  struct pointer_query_columns< ::hourly_income, id_sqlite, A >:
    pointer_query_columns< ::income, id_sqlite, A >
  {
    // income
    //
    typedef pointer_query_columns< ::income, id_sqlite, A > income;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // hours
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    hours_type_;

    static const hours_type_ hours;
  };

  template <typename A>
  const typename pointer_query_columns< ::hourly_income, id_sqlite, A >::id_type_
  pointer_query_columns< ::hourly_income, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::hourly_income, id_sqlite, A >::hours_type_
  pointer_query_columns< ::hourly_income, id_sqlite, A >::
  hours (A::table_name, "\"hours\"", 0);

  template <>
  class access::object_traits_impl< ::hourly_income, id_sqlite >:
    public access::object_traits< ::hourly_income >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::income, id_sqlite >::image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      // _hours
      //
      double _hours_value;
      bool _hours_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 5UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::hourly_income, id_common >:
    public access::object_traits_impl< ::hourly_income, id_sqlite >
  {
  };

  // income
  //
  template <>
  struct alias_traits<
    ::account,
    id_sqlite,
    access::object_traits_impl< ::income, id_sqlite >::to_acct_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::income, id_sqlite >
  {
    // to_acct
    //
    typedef
    odb::alias_traits<
      ::account,
      id_sqlite,
      access::object_traits_impl< ::income, id_sqlite >::to_acct_tag>
    to_acct_alias_;
  };

  template <typename A>
  struct query_columns< ::income, id_sqlite, A >:
    query_columns_base< ::income, id_sqlite >
  {
    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // pay_frequency
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    pay_frequency_type_;

    static const pay_frequency_type_ pay_frequency;

    // to_acct
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    to_acct_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::account,
        id_sqlite,
        to_acct_alias_ > >
    to_acct_pointer_type_;

    struct to_acct_type_: to_acct_pointer_type_, to_acct_column_type_
    {
      to_acct_type_ (const char* t, const char* c, const char* conv)
        : to_acct_column_type_ (t, c, conv)
      {
      }
    };

    static const to_acct_type_ to_acct;
  };

  template <typename A>
  const typename query_columns< ::income, id_sqlite, A >::amount_type_
  query_columns< ::income, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename query_columns< ::income, id_sqlite, A >::pay_frequency_type_
  query_columns< ::income, id_sqlite, A >::
  pay_frequency (A::table_name, "\"pay_frequency\"", 0);

  template <typename A>
  const typename query_columns< ::income, id_sqlite, A >::to_acct_type_
  query_columns< ::income, id_sqlite, A >::
  to_acct (A::table_name, "\"to_acct\"", 0);

  // salaried_income
  //
  template <typename A>
  struct query_columns< ::salaried_income, id_sqlite, A >:
    query_columns< ::income, id_sqlite, A >
  {
    // income
    //
    typedef query_columns< ::income, id_sqlite, A > income;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::salaried_income, id_sqlite, A >::id_type_
  query_columns< ::salaried_income, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  // hourly_income
  //
  template <typename A>
  struct query_columns< ::hourly_income, id_sqlite, A >:
    query_columns< ::income, id_sqlite, A >
  {
    // income
    //
    typedef query_columns< ::income, id_sqlite, A > income;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // hours
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    hours_type_;

    static const hours_type_ hours;
  };

  template <typename A>
  const typename query_columns< ::hourly_income, id_sqlite, A >::id_type_
  query_columns< ::hourly_income, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::hourly_income, id_sqlite, A >::hours_type_
  query_columns< ::hourly_income, id_sqlite, A >::
  hours (A::table_name, "\"hours\"", 0);
}

#include "../i/income-odb.ixx"

#include <odb/post.hxx>

#endif // INCOME_ODB_HXX
