// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef INVESTMENT_ODB_HXX
#define INVESTMENT_ODB_HXX

#include <odb/version.hxx>

#if (ODB_VERSION != 20400UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "model/investment.hxx"

#include "account-odb.hxx"
#include "auth_user-odb.hxx"
#include "family-odb.hxx"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // investment
  //
  template <>
  struct class_traits< ::investment >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::investment >
  {
    public:
    typedef ::investment object_type;
    typedef ::investment* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    static const bool abstract = true;
  };

  // stock
  //
  template <>
  struct class_traits< ::stock >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::stock >
  {
    public:
    typedef ::stock object_type;
    typedef ::stock* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // bond
  //
  template <>
  struct class_traits< ::bond >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::bond >
  {
    public:
    typedef ::bond object_type;
    typedef ::bond* pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef unsigned int id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/sqlite/version.hxx>
#include <odb/sqlite/forward.hxx>
#include <odb/sqlite/binding.hxx>
#include <odb/sqlite/sqlite-types.hxx>
#include <odb/sqlite/query.hxx>

namespace odb
{
  // investment
  //
  template <typename A>
  struct pointer_query_columns< ::investment, id_sqlite, A >
  {
    // buy_date
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    buy_date_type_;

    static const buy_date_type_ buy_date;

    // acct
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    acct_type_;

    static const acct_type_ acct;

    // owner
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    owner_type_;

    static const owner_type_ owner;
  };

  template <typename A>
  const typename pointer_query_columns< ::investment, id_sqlite, A >::buy_date_type_
  pointer_query_columns< ::investment, id_sqlite, A >::
  buy_date (A::table_name, "\"buy_date\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::investment, id_sqlite, A >::acct_type_
  pointer_query_columns< ::investment, id_sqlite, A >::
  acct (A::table_name, "\"acct\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::investment, id_sqlite, A >::owner_type_
  pointer_query_columns< ::investment, id_sqlite, A >::
  owner (A::table_name, "\"owner\"", 0);

  template <>
  class access::object_traits_impl< ::investment, id_sqlite >:
    public access::object_traits< ::investment >
  {
    public:
    struct image_type
    {
      // _buy_date
      //
      long long _buy_date_value;
      bool _buy_date_null;

      // _acct
      //
      long long _acct_value;
      bool _acct_null;

      // _owner
      //
      details::buffer _owner_value;
      std::size_t _owner_size;
      bool _owner_null;
    };

    struct acct_tag;
    struct owner_tag;

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);
  };

  // stock
  //
  template <typename A>
  struct pointer_query_columns< ::stock, id_sqlite, A >:
    pointer_query_columns< ::investment, id_sqlite, A >
  {
    // investment
    //
    typedef pointer_query_columns< ::investment, id_sqlite, A > investment;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // ticker
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    ticker_type_;

    static const ticker_type_ ticker;

    // buy_price
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    buy_price_type_;

    static const buy_price_type_ buy_price;

    // num_shares
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    num_shares_type_;

    static const num_shares_type_ num_shares;

    // dividend
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    dividend_type_;

    static const dividend_type_ dividend;
  };

  template <typename A>
  const typename pointer_query_columns< ::stock, id_sqlite, A >::id_type_
  pointer_query_columns< ::stock, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::stock, id_sqlite, A >::ticker_type_
  pointer_query_columns< ::stock, id_sqlite, A >::
  ticker (A::table_name, "\"ticker\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::stock, id_sqlite, A >::buy_price_type_
  pointer_query_columns< ::stock, id_sqlite, A >::
  buy_price (A::table_name, "\"buy_price\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::stock, id_sqlite, A >::num_shares_type_
  pointer_query_columns< ::stock, id_sqlite, A >::
  num_shares (A::table_name, "\"num_shares\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::stock, id_sqlite, A >::dividend_type_
  pointer_query_columns< ::stock, id_sqlite, A >::
  dividend (A::table_name, "\"dividend\"", 0);

  template <>
  class access::object_traits_impl< ::stock, id_sqlite >:
    public access::object_traits< ::stock >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::investment, id_sqlite >::image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      // _ticker
      //
      details::buffer _ticker_value;
      std::size_t _ticker_size;
      bool _ticker_null;

      // _buy_price
      //
      double _buy_price_value;
      bool _buy_price_null;

      // _num_shares
      //
      double _num_shares_value;
      bool _num_shares_null;

      // _dividend
      //
      double _dividend_value;
      bool _dividend_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 8UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::stock, id_common >:
    public access::object_traits_impl< ::stock, id_sqlite >
  {
  };

  // bond
  //
  template <typename A>
  struct pointer_query_columns< ::bond, id_sqlite, A >:
    pointer_query_columns< ::investment, id_sqlite, A >
  {
    // investment
    //
    typedef pointer_query_columns< ::investment, id_sqlite, A > investment;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // interest
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    interest_type_;

    static const interest_type_ interest;

    // maturity_date
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    maturity_date_type_;

    static const maturity_date_type_ maturity_date;
  };

  template <typename A>
  const typename pointer_query_columns< ::bond, id_sqlite, A >::id_type_
  pointer_query_columns< ::bond, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::bond, id_sqlite, A >::amount_type_
  pointer_query_columns< ::bond, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::bond, id_sqlite, A >::interest_type_
  pointer_query_columns< ::bond, id_sqlite, A >::
  interest (A::table_name, "\"interest\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::bond, id_sqlite, A >::maturity_date_type_
  pointer_query_columns< ::bond, id_sqlite, A >::
  maturity_date (A::table_name, "\"maturity_date\"", 0);

  template <>
  class access::object_traits_impl< ::bond, id_sqlite >:
    public access::object_traits< ::bond >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type: object_traits_impl< ::investment, id_sqlite >::image_type
    {
      // _id
      //
      long long _id_value;
      bool _id_null;

      // _amount
      //
      double _amount_value;
      bool _amount_null;

      // _interest
      //
      double _interest_value;
      bool _interest_null;

      // _maturity_date
      //
      long long _maturity_date_value;
      bool _maturity_date_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (sqlite::bind*,
          image_type&,
          sqlite::statement_kind);

    static void
    bind (sqlite::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          sqlite::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef sqlite::object_statements<object_type> statements_type;

    typedef sqlite::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::bond, id_common >:
    public access::object_traits_impl< ::bond, id_sqlite >
  {
  };

  // investment
  //
  template <>
  struct alias_traits<
    ::account,
    id_sqlite,
    access::object_traits_impl< ::investment, id_sqlite >::acct_tag>
  {
    static const char table_name[];
  };

  template <>
  struct alias_traits<
    ::auth_user,
    id_sqlite,
    access::object_traits_impl< ::investment, id_sqlite >::owner_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::investment, id_sqlite >
  {
    // acct
    //
    typedef
    odb::alias_traits<
      ::account,
      id_sqlite,
      access::object_traits_impl< ::investment, id_sqlite >::acct_tag>
    acct_alias_;

    // owner
    //
    typedef
    odb::alias_traits<
      ::auth_user,
      id_sqlite,
      access::object_traits_impl< ::investment, id_sqlite >::owner_tag>
    owner_alias_;
  };

  template <typename A>
  struct query_columns< ::investment, id_sqlite, A >:
    query_columns_base< ::investment, id_sqlite >
  {
    // buy_date
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    buy_date_type_;

    static const buy_date_type_ buy_date;

    // acct
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        long int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    acct_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::account,
        id_sqlite,
        acct_alias_ > >
    acct_pointer_type_;

    struct acct_type_: acct_pointer_type_, acct_column_type_
    {
      acct_type_ (const char* t, const char* c, const char* conv)
        : acct_column_type_ (t, c, conv)
      {
      }
    };

    static const acct_type_ acct;

    // owner
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    owner_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::auth_user,
        id_sqlite,
        owner_alias_ > >
    owner_pointer_type_;

    struct owner_type_: owner_pointer_type_, owner_column_type_
    {
      owner_type_ (const char* t, const char* c, const char* conv)
        : owner_column_type_ (t, c, conv)
      {
      }
    };

    static const owner_type_ owner;
  };

  template <typename A>
  const typename query_columns< ::investment, id_sqlite, A >::buy_date_type_
  query_columns< ::investment, id_sqlite, A >::
  buy_date (A::table_name, "\"buy_date\"", 0);

  template <typename A>
  const typename query_columns< ::investment, id_sqlite, A >::acct_type_
  query_columns< ::investment, id_sqlite, A >::
  acct (A::table_name, "\"acct\"", 0);

  template <typename A>
  const typename query_columns< ::investment, id_sqlite, A >::owner_type_
  query_columns< ::investment, id_sqlite, A >::
  owner (A::table_name, "\"owner\"", 0);

  // stock
  //
  template <typename A>
  struct query_columns< ::stock, id_sqlite, A >:
    query_columns< ::investment, id_sqlite, A >
  {
    // investment
    //
    typedef query_columns< ::investment, id_sqlite, A > investment;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // ticker
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::std::string,
        sqlite::id_text >::query_type,
      sqlite::id_text >
    ticker_type_;

    static const ticker_type_ ticker;

    // buy_price
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    buy_price_type_;

    static const buy_price_type_ buy_price;

    // num_shares
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    num_shares_type_;

    static const num_shares_type_ num_shares;

    // dividend
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    dividend_type_;

    static const dividend_type_ dividend;
  };

  template <typename A>
  const typename query_columns< ::stock, id_sqlite, A >::id_type_
  query_columns< ::stock, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::stock, id_sqlite, A >::ticker_type_
  query_columns< ::stock, id_sqlite, A >::
  ticker (A::table_name, "\"ticker\"", 0);

  template <typename A>
  const typename query_columns< ::stock, id_sqlite, A >::buy_price_type_
  query_columns< ::stock, id_sqlite, A >::
  buy_price (A::table_name, "\"buy_price\"", 0);

  template <typename A>
  const typename query_columns< ::stock, id_sqlite, A >::num_shares_type_
  query_columns< ::stock, id_sqlite, A >::
  num_shares (A::table_name, "\"num_shares\"", 0);

  template <typename A>
  const typename query_columns< ::stock, id_sqlite, A >::dividend_type_
  query_columns< ::stock, id_sqlite, A >::
  dividend (A::table_name, "\"dividend\"", 0);

  // bond
  //
  template <typename A>
  struct query_columns< ::bond, id_sqlite, A >:
    query_columns< ::investment, id_sqlite, A >
  {
    // investment
    //
    typedef query_columns< ::investment, id_sqlite, A > investment;

    // id
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        unsigned int,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    id_type_;

    static const id_type_ id;

    // amount
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        double,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    amount_type_;

    static const amount_type_ amount;

    // interest
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        float,
        sqlite::id_real >::query_type,
      sqlite::id_real >
    interest_type_;

    static const interest_type_ interest;

    // maturity_date
    //
    typedef
    sqlite::query_column<
      sqlite::value_traits<
        ::time_t,
        sqlite::id_integer >::query_type,
      sqlite::id_integer >
    maturity_date_type_;

    static const maturity_date_type_ maturity_date;
  };

  template <typename A>
  const typename query_columns< ::bond, id_sqlite, A >::id_type_
  query_columns< ::bond, id_sqlite, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::bond, id_sqlite, A >::amount_type_
  query_columns< ::bond, id_sqlite, A >::
  amount (A::table_name, "\"amount\"", 0);

  template <typename A>
  const typename query_columns< ::bond, id_sqlite, A >::interest_type_
  query_columns< ::bond, id_sqlite, A >::
  interest (A::table_name, "\"interest\"", 0);

  template <typename A>
  const typename query_columns< ::bond, id_sqlite, A >::maturity_date_type_
  query_columns< ::bond, id_sqlite, A >::
  maturity_date (A::table_name, "\"maturity_date\"", 0);
}

#include "../i/investment-odb.ixx"

#include <odb/post.hxx>

#endif // INVESTMENT_ODB_HXX
