// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "account-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // account
  //

  const char alias_traits<  ::auth_user,
    id_sqlite,
    access::object_traits_impl< ::account, id_sqlite >::owner_tag>::
  table_name[] = "\"owner\"";

  const char alias_traits<  ::auth_user,
    id_sqlite,
    access::object_traits_impl< ::account, id_sqlite >::custodian_tag>::
  table_name[] = "\"custodian\"";

  struct access::object_traits_impl< ::account, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::account, id_sqlite >::id_type
  access::object_traits_impl< ::account, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_value (
        id,
        i._acct_num_value,
        i._acct_num_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::account, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _acct_num
    //
    t[0UL] = false;

    // _balance
    //
    t[1UL] = false;

    // _interest
    //
    t[2UL] = false;

    // _owner
    //
    if (t[3UL])
    {
      i._owner_value.capacity (i._owner_size);
      grew = true;
    }

    // _custodian
    //
    if (t[4UL])
    {
      i._custodian_value.capacity (i._custodian_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // _acct_num
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._acct_num_value;
      b[n].is_null = &i._acct_num_null;
      n++;
    }

    // _balance
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._balance_value;
    b[n].is_null = &i._balance_null;
    n++;

    // _interest
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._interest_value;
    b[n].is_null = &i._interest_null;
    n++;

    // _owner
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._owner_value.data ();
    b[n].size = &i._owner_size;
    b[n].capacity = i._owner_value.capacity ();
    b[n].is_null = &i._owner_null;
    n++;

    // _custodian
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._custodian_value.data ();
    b[n].size = &i._custodian_size;
    b[n].capacity = i._custodian_value.capacity ();
    b[n].is_null = &i._custodian_null;
    n++;
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::account, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // _acct_num
    //
    if (sk == statement_insert)
    {
      long int const& v =
        o._acct_num;

      bool is_null (false);
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_image (
        i._acct_num_value,
        is_null,
        v);
      i._acct_num_null = is_null;
    }

    // _balance
    //
    {
      double const& v =
        o._balance;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._balance_value,
        is_null,
        v);
      i._balance_null = is_null;
    }

    // _interest
    //
    {
      float const& v =
        o._interest;

      bool is_null (true);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i._interest_value,
        is_null,
        v);
      i._interest_null = is_null;
    }

    // _owner
    //
    {
      ::std::shared_ptr< ::auth_user > const& v =
        o._owner;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        std::size_t cap (i._owner_value.capacity ());
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_image (
          i._owner_value,
          i._owner_size,
          is_null,
          id);
        i._owner_null = is_null;
        grew = grew || (cap != i._owner_value.capacity ());
      }
      else
        throw null_pointer ();
    }

    // _custodian
    //
    {
      ::std::shared_ptr< ::auth_user > const& v =
        o._custodian;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        std::size_t cap (i._custodian_value.capacity ());
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_image (
          i._custodian_value,
          i._custodian_size,
          is_null,
          id);
        i._custodian_null = is_null;
        grew = grew || (cap != i._custodian_value.capacity ());
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _acct_num
    //
    {
      long int& v =
        o._acct_num;

      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_value (
        v,
        i._acct_num_value,
        i._acct_num_null);
    }

    // _balance
    //
    {
      double& v =
        o._balance;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._balance_value,
        i._balance_null);
    }

    // _interest
    //
    {
      float& v =
        o._interest;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i._interest_value,
        i._interest_null);
    }

    // _owner
    //
    {
      ::std::shared_ptr< ::auth_user >& v =
        o._owner;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      if (i._owner_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_value (
          id,
          i._owner_value,
          i._owner_size,
          i._owner_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }

    // _custodian
    //
    {
      ::std::shared_ptr< ::auth_user >& v =
        o._custodian;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      if (i._custodian_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_value (
          id,
          i._custodian_value,
          i._custodian_size,
          i._custodian_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          long int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::account, id_sqlite >::persist_statement[] =
  "INSERT INTO \"account\" "
  "(\"acct_num\", "
  "\"balance\", "
  "\"interest\", "
  "\"owner\", "
  "\"custodian\") "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::account, id_sqlite >::find_statement[] =
  "SELECT "
  "\"account\".\"acct_num\", "
  "\"account\".\"balance\", "
  "\"account\".\"interest\", "
  "\"account\".\"owner\", "
  "\"account\".\"custodian\" "
  "FROM \"account\" "
  "WHERE \"account\".\"acct_num\"=?";

  const char access::object_traits_impl< ::account, id_sqlite >::update_statement[] =
  "UPDATE \"account\" "
  "SET "
  "\"balance\"=?, "
  "\"interest\"=?, "
  "\"owner\"=?, "
  "\"custodian\"=? "
  "WHERE \"acct_num\"=?";

  const char access::object_traits_impl< ::account, id_sqlite >::erase_statement[] =
  "DELETE FROM \"account\" "
  "WHERE \"acct_num\"=?";

  const char access::object_traits_impl< ::account, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"account\".\"acct_num\",\n"
  "\"account\".\"balance\",\n"
  "\"account\".\"interest\",\n"
  "\"account\".\"owner\",\n"
  "\"account\".\"custodian\"\n"
  "FROM \"account\"\n"
  "LEFT JOIN \"auth_user\" AS \"owner\" ON \"owner\".\"username\"=\"account\".\"owner\"\n"
  "LEFT JOIN \"auth_user\" AS \"custodian\" ON \"custodian\".\"username\"=\"account\".\"custodian\"";

  const char access::object_traits_impl< ::account, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"account\"";

  const char access::object_traits_impl< ::account, id_sqlite >::table_name[] =
  "\"account\"";

  void access::object_traits_impl< ::account, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._acct_num);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::account, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::account, id_sqlite >::pointer_type
  access::object_traits_impl< ::account, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::account, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::account, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._acct_num);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::account, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::account, id_sqlite >::object_type >
  access::object_traits_impl< ::account, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::account, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // retirement_account
  //

  struct access::object_traits_impl< ::retirement_account, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  bool access::object_traits_impl< ::retirement_account, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // account base
    //
    if (object_traits_impl< ::account, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::retirement_account, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // account base
    //
    object_traits_impl< ::account, id_sqlite >::bind (b + n, i, sk);
    n += sk == statement_update ? 4UL : 5UL;
  }

  bool access::object_traits_impl< ::retirement_account, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // account base
    //
    if (object_traits_impl< ::account, id_sqlite >::init (i, o, sk))
      grew = true;

    return grew;
  }

  void access::object_traits_impl< ::retirement_account, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // account base
    //
    object_traits_impl< ::account, id_sqlite >::init (o, i, db);
  }

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::persist_statement[] =
  "INSERT INTO \"retirement_account\" "
  "(\"acct_num\", "
  "\"balance\", "
  "\"interest\", "
  "\"owner\", "
  "\"custodian\") "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::find_statement[] =
  "SELECT "
  "\"retirement_account\".\"acct_num\", "
  "\"retirement_account\".\"balance\", "
  "\"retirement_account\".\"interest\", "
  "\"retirement_account\".\"owner\", "
  "\"retirement_account\".\"custodian\" "
  "FROM \"retirement_account\" "
  "WHERE \"retirement_account\".\"acct_num\"=?";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::update_statement[] =
  "UPDATE \"retirement_account\" "
  "SET "
  "\"balance\"=?, "
  "\"interest\"=?, "
  "\"owner\"=?, "
  "\"custodian\"=? "
  "WHERE \"acct_num\"=?";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::erase_statement[] =
  "DELETE FROM \"retirement_account\" "
  "WHERE \"acct_num\"=?";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"retirement_account\".\"acct_num\",\n"
  "\"retirement_account\".\"balance\",\n"
  "\"retirement_account\".\"interest\",\n"
  "\"retirement_account\".\"owner\",\n"
  "\"retirement_account\".\"custodian\"\n"
  "FROM \"retirement_account\"\n"
  "LEFT JOIN \"auth_user\" AS \"owner\" ON \"owner\".\"username\"=\"retirement_account\".\"owner\"\n"
  "LEFT JOIN \"auth_user\" AS \"custodian\" ON \"custodian\".\"username\"=\"retirement_account\".\"custodian\"";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"retirement_account\"";

  const char access::object_traits_impl< ::retirement_account, id_sqlite >::table_name[] =
  "\"retirement_account\"";

  void access::object_traits_impl< ::retirement_account, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::retirement_account, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._acct_num);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::retirement_account, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::retirement_account, id_sqlite >::pointer_type
  access::object_traits_impl< ::retirement_account, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::retirement_account, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::retirement_account, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._acct_num);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::retirement_account, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::retirement_account, id_sqlite >::object_type >
  access::object_traits_impl< ::retirement_account, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::retirement_account, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"retirement_account\"");
          db.execute ("DROP TABLE IF EXISTS \"account\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"account\" (\n"
                      "  \"acct_num\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"balance\" REAL NULL,\n"
                      "  \"interest\" REAL NULL,\n"
                      "  \"owner\" TEXT NOT NULL,\n"
                      "  \"custodian\" TEXT NOT NULL,\n"
                      "  CONSTRAINT \"owner_fk\"\n"
                      "    FOREIGN KEY (\"owner\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED,\n"
                      "  CONSTRAINT \"custodian_fk\"\n"
                      "    FOREIGN KEY (\"custodian\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE TABLE \"retirement_account\" (\n"
                      "  \"acct_num\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"balance\" REAL NULL,\n"
                      "  \"interest\" REAL NULL,\n"
                      "  \"owner\" TEXT NOT NULL,\n"
                      "  \"custodian\" TEXT NOT NULL,\n"
                      "  CONSTRAINT \"owner_fk\"\n"
                      "    FOREIGN KEY (\"owner\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED,\n"
                      "  CONSTRAINT \"custodian_fk\"\n"
                      "    FOREIGN KEY (\"custodian\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
