// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "debt-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // debt
  //

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::debt, id_sqlite >::from_acct_tag>::
  table_name[] = "\"from_acct\"";

  bool access::object_traits_impl< ::debt, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _principal
    //
    t[0UL] = false;

    // _interest
    //
    t[1UL] = false;

    // _start_date
    //
    t[2UL] = false;

    // _end_date
    //
    t[3UL] = false;

    // _type
    //
    if (t[4UL])
    {
      i._type_value.capacity (i._type_size);
      grew = true;
    }

    // _from_acct
    //
    t[5UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::debt, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // _principal
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._principal_value;
    b[n].is_null = &i._principal_null;
    n++;

    // _interest
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._interest_value;
    b[n].is_null = &i._interest_null;
    n++;

    // _start_date
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._start_date_value;
    b[n].is_null = &i._start_date_null;
    n++;

    // _end_date
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._end_date_value;
    b[n].is_null = &i._end_date_null;
    n++;

    // _type
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._type_value.data ();
    b[n].size = &i._type_size;
    b[n].capacity = i._type_value.capacity ();
    b[n].is_null = &i._type_null;
    n++;

    // _from_acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._from_acct_value;
    b[n].is_null = &i._from_acct_null;
    n++;
  }

  bool access::object_traits_impl< ::debt, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // _principal
    //
    {
      double const& v =
        o._principal;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._principal_value,
        is_null,
        v);
      i._principal_null = is_null;
    }

    // _interest
    //
    {
      float const& v =
        o._interest;

      bool is_null (true);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i._interest_value,
        is_null,
        v);
      i._interest_null = is_null;
    }

    // _start_date
    //
    {
      ::time_t const& v =
        o._start_date;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i._start_date_value,
        is_null,
        v);
      i._start_date_null = is_null;
    }

    // _end_date
    //
    {
      ::time_t const& v =
        o._end_date;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i._end_date_value,
        is_null,
        v);
      i._end_date_null = is_null;
    }

    // _type
    //
    {
      ::std::string const& v =
        o._type;

      bool is_null (false);
      std::size_t cap (i._type_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i._type_value,
        i._type_size,
        is_null,
        v);
      i._type_null = is_null;
      grew = grew || (cap != i._type_value.capacity ());
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._from_acct_value,
          is_null,
          id);
        i._from_acct_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::debt, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _principal
    //
    {
      double& v =
        o._principal;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._principal_value,
        i._principal_null);
    }

    // _interest
    //
    {
      float& v =
        o._interest;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i._interest_value,
        i._interest_null);
    }

    // _start_date
    //
    {
      ::time_t& v =
        o._start_date;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i._start_date_value,
        i._start_date_null);
    }

    // _end_date
    //
    {
      ::time_t& v =
        o._end_date;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i._end_date_value,
        i._end_date_null);
    }

    // _type
    //
    {
      ::std::string& v =
        o._type;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i._type_value,
        i._type_size,
        i._type_null);
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._from_acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._from_acct_value,
          i._from_acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  // mortgage
  //

  struct access::object_traits_impl< ::mortgage, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::mortgage, id_sqlite >::id_type
  access::object_traits_impl< ::mortgage, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::mortgage, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // debt base
    //
    if (object_traits_impl< ::debt, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[6UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // debt base
    //
    object_traits_impl< ::debt, id_sqlite >::bind (b + n, i, sk);
    n += 6UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::mortgage, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // debt base
    //
    if (object_traits_impl< ::debt, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // debt base
    //
    object_traits_impl< ::debt, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::mortgage, id_sqlite >::persist_statement[] =
  "INSERT INTO \"mortgage\" "
  "(\"principal\", "
  "\"interest\", "
  "\"start_date\", "
  "\"end_date\", "
  "\"type\", "
  "\"from_acct\", "
  "\"id\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::find_statement[] =
  "SELECT "
  "\"mortgage\".\"principal\", "
  "\"mortgage\".\"interest\", "
  "\"mortgage\".\"start_date\", "
  "\"mortgage\".\"end_date\", "
  "\"mortgage\".\"type\", "
  "\"mortgage\".\"from_acct\", "
  "\"mortgage\".\"id\" "
  "FROM \"mortgage\" "
  "WHERE \"mortgage\".\"id\"=?";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::update_statement[] =
  "UPDATE \"mortgage\" "
  "SET "
  "\"principal\"=?, "
  "\"interest\"=?, "
  "\"start_date\"=?, "
  "\"end_date\"=?, "
  "\"type\"=?, "
  "\"from_acct\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::erase_statement[] =
  "DELETE FROM \"mortgage\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"mortgage\".\"principal\",\n"
  "\"mortgage\".\"interest\",\n"
  "\"mortgage\".\"start_date\",\n"
  "\"mortgage\".\"end_date\",\n"
  "\"mortgage\".\"type\",\n"
  "\"mortgage\".\"from_acct\",\n"
  "\"mortgage\".\"id\"\n"
  "FROM \"mortgage\"\n"
  "LEFT JOIN \"account\" AS \"from_acct\" ON \"from_acct\".\"acct_num\"=\"mortgage\".\"from_acct\"";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"mortgage\"";

  const char access::object_traits_impl< ::mortgage, id_sqlite >::table_name[] =
  "\"mortgage\"";

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::mortgage, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::mortgage, id_sqlite >::pointer_type
  access::object_traits_impl< ::mortgage, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::mortgage, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::mortgage, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::mortgage, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::mortgage, id_sqlite >::object_type >
  access::object_traits_impl< ::mortgage, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::mortgage, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"mortgage\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"mortgage\" (\n"
                      "  \"principal\" REAL NULL,\n"
                      "  \"interest\" REAL NULL,\n"
                      "  \"start_date\" INTEGER NOT NULL,\n"
                      "  \"end_date\" INTEGER NOT NULL,\n"
                      "  \"type\" TEXT NOT NULL,\n"
                      "  \"from_acct\" INTEGER NOT NULL,\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  CONSTRAINT \"from_acct_fk\"\n"
                      "    FOREIGN KEY (\"from_acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
