// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "investment-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // investment
  //

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::investment, id_sqlite >::acct_tag>::
  table_name[] = "\"acct\"";

  const char alias_traits<  ::auth_user,
    id_sqlite,
    access::object_traits_impl< ::investment, id_sqlite >::owner_tag>::
  table_name[] = "\"owner\"";

  bool access::object_traits_impl< ::investment, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _buy_date
    //
    t[0UL] = false;

    // _acct
    //
    t[1UL] = false;

    // _owner
    //
    if (t[2UL])
    {
      i._owner_value.capacity (i._owner_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::investment, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // _buy_date
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._buy_date_value;
    b[n].is_null = &i._buy_date_null;
    n++;

    // _acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._acct_value;
    b[n].is_null = &i._acct_null;
    n++;

    // _owner
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._owner_value.data ();
    b[n].size = &i._owner_size;
    b[n].capacity = i._owner_value.capacity ();
    b[n].is_null = &i._owner_null;
    n++;
  }

  bool access::object_traits_impl< ::investment, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // _buy_date
    //
    {
      ::time_t const& v =
        o._buy_date;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i._buy_date_value,
        is_null,
        v);
      i._buy_date_null = is_null;
    }

    // _acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._acct_value,
          is_null,
          id);
        i._acct_null = is_null;
      }
      else
        i._acct_null = true;
    }

    // _owner
    //
    {
      ::std::shared_ptr< ::auth_user > const& v =
        o._owner;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        std::size_t cap (i._owner_value.capacity ());
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_image (
          i._owner_value,
          i._owner_size,
          is_null,
          id);
        i._owner_null = is_null;
        grew = grew || (cap != i._owner_value.capacity ());
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::investment, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _buy_date
    //
    {
      ::time_t& v =
        o._buy_date;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i._buy_date_value,
        i._buy_date_null);
    }

    // _acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._acct_value,
          i._acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }

    // _owner
    //
    {
      ::std::shared_ptr< ::auth_user >& v =
        o._owner;

      typedef object_traits< ::auth_user > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::auth_user > > ptr_traits;

      if (i._owner_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_text >::set_value (
          id,
          i._owner_value,
          i._owner_size,
          i._owner_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  // stock
  //

  struct access::object_traits_impl< ::stock, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::stock, id_sqlite >::id_type
  access::object_traits_impl< ::stock, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::stock, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // investment base
    //
    if (object_traits_impl< ::investment, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[3UL] = false;

    // _ticker
    //
    if (t[4UL])
    {
      i._ticker_value.capacity (i._ticker_size);
      grew = true;
    }

    // _buy_price
    //
    t[5UL] = false;

    // _num_shares
    //
    t[6UL] = false;

    // _dividend
    //
    t[7UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // investment base
    //
    object_traits_impl< ::investment, id_sqlite >::bind (b + n, i, sk);
    n += 3UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _ticker
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._ticker_value.data ();
    b[n].size = &i._ticker_size;
    b[n].capacity = i._ticker_value.capacity ();
    b[n].is_null = &i._ticker_null;
    n++;

    // _buy_price
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._buy_price_value;
    b[n].is_null = &i._buy_price_null;
    n++;

    // _num_shares
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._num_shares_value;
    b[n].is_null = &i._num_shares_null;
    n++;

    // _dividend
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._dividend_value;
    b[n].is_null = &i._dividend_null;
    n++;
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::stock, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // investment base
    //
    if (object_traits_impl< ::investment, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    // _ticker
    //
    {
      ::std::string const& v =
        o._ticker;

      bool is_null (false);
      std::size_t cap (i._ticker_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i._ticker_value,
        i._ticker_size,
        is_null,
        v);
      i._ticker_null = is_null;
      grew = grew || (cap != i._ticker_value.capacity ());
    }

    // _buy_price
    //
    {
      double const& v =
        o._buy_price;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._buy_price_value,
        is_null,
        v);
      i._buy_price_null = is_null;
    }

    // _num_shares
    //
    {
      double const& v =
        o._num_shares;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._num_shares_value,
        is_null,
        v);
      i._num_shares_null = is_null;
    }

    // _dividend
    //
    {
      float const& v =
        o._dividend;

      bool is_null (true);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i._dividend_value,
        is_null,
        v);
      i._dividend_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // investment base
    //
    object_traits_impl< ::investment, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _ticker
    //
    {
      ::std::string& v =
        o._ticker;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i._ticker_value,
        i._ticker_size,
        i._ticker_null);
    }

    // _buy_price
    //
    {
      double& v =
        o._buy_price;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._buy_price_value,
        i._buy_price_null);
    }

    // _num_shares
    //
    {
      double& v =
        o._num_shares;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._num_shares_value,
        i._num_shares_null);
    }

    // _dividend
    //
    {
      float& v =
        o._dividend;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i._dividend_value,
        i._dividend_null);
    }
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::stock, id_sqlite >::persist_statement[] =
  "INSERT INTO \"stock\" "
  "(\"buy_date\", "
  "\"acct\", "
  "\"owner\", "
  "\"id\", "
  "\"ticker\", "
  "\"buy_price\", "
  "\"num_shares\", "
  "\"dividend\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::stock, id_sqlite >::find_statement[] =
  "SELECT "
  "\"stock\".\"buy_date\", "
  "\"stock\".\"acct\", "
  "\"stock\".\"owner\", "
  "\"stock\".\"id\", "
  "\"stock\".\"ticker\", "
  "\"stock\".\"buy_price\", "
  "\"stock\".\"num_shares\", "
  "\"stock\".\"dividend\" "
  "FROM \"stock\" "
  "WHERE \"stock\".\"id\"=?";

  const char access::object_traits_impl< ::stock, id_sqlite >::update_statement[] =
  "UPDATE \"stock\" "
  "SET "
  "\"buy_date\"=?, "
  "\"acct\"=?, "
  "\"owner\"=?, "
  "\"ticker\"=?, "
  "\"buy_price\"=?, "
  "\"num_shares\"=?, "
  "\"dividend\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::stock, id_sqlite >::erase_statement[] =
  "DELETE FROM \"stock\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::stock, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"stock\".\"buy_date\",\n"
  "\"stock\".\"acct\",\n"
  "\"stock\".\"owner\",\n"
  "\"stock\".\"id\",\n"
  "\"stock\".\"ticker\",\n"
  "\"stock\".\"buy_price\",\n"
  "\"stock\".\"num_shares\",\n"
  "\"stock\".\"dividend\"\n"
  "FROM \"stock\"\n"
  "LEFT JOIN \"account\" AS \"acct\" ON \"acct\".\"acct_num\"=\"stock\".\"acct\"\n"
  "LEFT JOIN \"auth_user\" AS \"owner\" ON \"owner\".\"username\"=\"stock\".\"owner\"";

  const char access::object_traits_impl< ::stock, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"stock\"";

  const char access::object_traits_impl< ::stock, id_sqlite >::table_name[] =
  "\"stock\"";

  void access::object_traits_impl< ::stock, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::stock, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::stock, id_sqlite >::pointer_type
  access::object_traits_impl< ::stock, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::stock, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::stock, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::stock, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::stock, id_sqlite >::object_type >
  access::object_traits_impl< ::stock, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::stock, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // bond
  //

  struct access::object_traits_impl< ::bond, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::bond, id_sqlite >::id_type
  access::object_traits_impl< ::bond, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::bond, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // investment base
    //
    if (object_traits_impl< ::investment, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[3UL] = false;

    // _amount
    //
    t[4UL] = false;

    // _interest
    //
    t[5UL] = false;

    // _maturity_date
    //
    t[6UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // investment base
    //
    object_traits_impl< ::investment, id_sqlite >::bind (b + n, i, sk);
    n += 3UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _amount
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._amount_value;
    b[n].is_null = &i._amount_null;
    n++;

    // _interest
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._interest_value;
    b[n].is_null = &i._interest_null;
    n++;

    // _maturity_date
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._maturity_date_value;
    b[n].is_null = &i._maturity_date_null;
    n++;
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::bond, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // investment base
    //
    if (object_traits_impl< ::investment, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    // _amount
    //
    {
      double const& v =
        o._amount;

      bool is_null (false);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._amount_value,
        is_null,
        v);
      i._amount_null = is_null;
    }

    // _interest
    //
    {
      float const& v =
        o._interest;

      bool is_null (false);
      sqlite::value_traits<
          float,
          sqlite::id_real >::set_image (
        i._interest_value,
        is_null,
        v);
      i._interest_null = is_null;
    }

    // _maturity_date
    //
    {
      ::time_t const& v =
        o._maturity_date;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i._maturity_date_value,
        is_null,
        v);
      i._maturity_date_null = is_null;
    }

    return grew;
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // investment base
    //
    object_traits_impl< ::investment, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _amount
    //
    {
      double& v =
        o._amount;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._amount_value,
        i._amount_null);
    }

    // _interest
    //
    {
      float& v =
        o._interest;

      sqlite::value_traits<
          float,
          sqlite::id_real >::set_value (
        v,
        i._interest_value,
        i._interest_null);
    }

    // _maturity_date
    //
    {
      ::time_t& v =
        o._maturity_date;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i._maturity_date_value,
        i._maturity_date_null);
    }
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::bond, id_sqlite >::persist_statement[] =
  "INSERT INTO \"bond\" "
  "(\"buy_date\", "
  "\"acct\", "
  "\"owner\", "
  "\"id\", "
  "\"amount\", "
  "\"interest\", "
  "\"maturity_date\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::bond, id_sqlite >::find_statement[] =
  "SELECT "
  "\"bond\".\"buy_date\", "
  "\"bond\".\"acct\", "
  "\"bond\".\"owner\", "
  "\"bond\".\"id\", "
  "\"bond\".\"amount\", "
  "\"bond\".\"interest\", "
  "\"bond\".\"maturity_date\" "
  "FROM \"bond\" "
  "WHERE \"bond\".\"id\"=?";

  const char access::object_traits_impl< ::bond, id_sqlite >::update_statement[] =
  "UPDATE \"bond\" "
  "SET "
  "\"buy_date\"=?, "
  "\"acct\"=?, "
  "\"owner\"=?, "
  "\"amount\"=?, "
  "\"interest\"=?, "
  "\"maturity_date\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::bond, id_sqlite >::erase_statement[] =
  "DELETE FROM \"bond\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::bond, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"bond\".\"buy_date\",\n"
  "\"bond\".\"acct\",\n"
  "\"bond\".\"owner\",\n"
  "\"bond\".\"id\",\n"
  "\"bond\".\"amount\",\n"
  "\"bond\".\"interest\",\n"
  "\"bond\".\"maturity_date\"\n"
  "FROM \"bond\"\n"
  "LEFT JOIN \"account\" AS \"acct\" ON \"acct\".\"acct_num\"=\"bond\".\"acct\"\n"
  "LEFT JOIN \"auth_user\" AS \"owner\" ON \"owner\".\"username\"=\"bond\".\"owner\"";

  const char access::object_traits_impl< ::bond, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"bond\"";

  const char access::object_traits_impl< ::bond, id_sqlite >::table_name[] =
  "\"bond\"";

  void access::object_traits_impl< ::bond, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::bond, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::bond, id_sqlite >::pointer_type
  access::object_traits_impl< ::bond, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::bond, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::bond, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::bond, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::bond, id_sqlite >::object_type >
  access::object_traits_impl< ::bond, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::bond, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"bond\"");
          db.execute ("DROP TABLE IF EXISTS \"stock\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"stock\" (\n"
                      "  \"buy_date\" INTEGER NOT NULL default current_timestamp,\n"
                      "  \"acct\" INTEGER NULL,\n"
                      "  \"owner\" TEXT NOT NULL,\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"ticker\" TEXT NOT NULL,\n"
                      "  \"buy_price\" REAL NOT NULL,\n"
                      "  \"num_shares\" REAL NOT NULL,\n"
                      "  \"dividend\" REAL NULL DEFAULT 0,\n"
                      "  CONSTRAINT \"acct_fk\"\n"
                      "    FOREIGN KEY (\"acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED,\n"
                      "  CONSTRAINT \"owner_fk\"\n"
                      "    FOREIGN KEY (\"owner\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE TABLE \"bond\" (\n"
                      "  \"buy_date\" INTEGER NOT NULL default current_timestamp,\n"
                      "  \"acct\" INTEGER NULL,\n"
                      "  \"owner\" TEXT NOT NULL,\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"amount\" REAL NOT NULL,\n"
                      "  \"interest\" REAL NOT NULL,\n"
                      "  \"maturity_date\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"acct_fk\"\n"
                      "    FOREIGN KEY (\"acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED,\n"
                      "  CONSTRAINT \"owner_fk\"\n"
                      "    FOREIGN KEY (\"owner\")\n"
                      "    REFERENCES \"auth_user\" (\"username\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
