// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#include <odb/pre.hxx>

#include "transaction-odb.hxx"

#include <cassert>
#include <cstring>  // std::memcpy

#include <odb/schema-catalog-impl.hxx>

#include <odb/sqlite/traits.hxx>
#include <odb/sqlite/database.hxx>
#include <odb/sqlite/transaction.hxx>
#include <odb/sqlite/connection.hxx>
#include <odb/sqlite/statement.hxx>
#include <odb/sqlite/statement-cache.hxx>
#include <odb/sqlite/simple-object-statements.hxx>
#include <odb/sqlite/container-statements.hxx>
#include <odb/sqlite/exceptions.hxx>
#include <odb/sqlite/simple-object-result.hxx>

namespace odb
{
  // transaction
  //

  bool access::object_traits_impl< ::transaction, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // _amount
    //
    t[0UL] = false;

    // _datetime
    //
    t[1UL] = false;

    // _description
    //
    if (t[2UL])
    {
      i._description_value.capacity (i._description_size);
      grew = true;
    }

    return grew;
  }

  void access::object_traits_impl< ::transaction, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // _amount
    //
    b[n].type = sqlite::bind::real;
    b[n].buffer = &i._amount_value;
    b[n].is_null = &i._amount_null;
    n++;

    // _datetime
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._datetime_value;
    b[n].is_null = &i._datetime_null;
    n++;

    // _description
    //
    b[n].type = sqlite::image_traits<
      ::std::string,
      sqlite::id_text>::bind_value;
    b[n].buffer = i._description_value.data ();
    b[n].size = &i._description_size;
    b[n].capacity = i._description_value.capacity ();
    b[n].is_null = &i._description_null;
    n++;
  }

  bool access::object_traits_impl< ::transaction, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // _amount
    //
    {
      double const& v =
        o._amount;

      bool is_null (true);
      sqlite::value_traits<
          double,
          sqlite::id_real >::set_image (
        i._amount_value,
        is_null,
        v);
      i._amount_null = is_null;
    }

    // _datetime
    //
    {
      ::time_t const& v =
        o._datetime;

      bool is_null (false);
      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_image (
        i._datetime_value,
        is_null,
        v);
      i._datetime_null = is_null;
    }

    // _description
    //
    {
      ::std::string const& v =
        o._description;

      bool is_null (false);
      std::size_t cap (i._description_value.capacity ());
      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_image (
        i._description_value,
        i._description_size,
        is_null,
        v);
      i._description_null = is_null;
      grew = grew || (cap != i._description_value.capacity ());
    }

    return grew;
  }

  void access::object_traits_impl< ::transaction, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // _amount
    //
    {
      double& v =
        o._amount;

      sqlite::value_traits<
          double,
          sqlite::id_real >::set_value (
        v,
        i._amount_value,
        i._amount_null);
    }

    // _datetime
    //
    {
      ::time_t& v =
        o._datetime;

      sqlite::value_traits<
          ::time_t,
          sqlite::id_integer >::set_value (
        v,
        i._datetime_value,
        i._datetime_null);
    }

    // _description
    //
    {
      ::std::string& v =
        o._description;

      sqlite::value_traits<
          ::std::string,
          sqlite::id_text >::set_value (
        v,
        i._description_value,
        i._description_size,
        i._description_null);
    }
  }

  // withdrawal
  //

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::withdrawal, id_sqlite >::from_acct_tag>::
  table_name[] = "\"from_acct\"";

  struct access::object_traits_impl< ::withdrawal, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::withdrawal, id_sqlite >::id_type
  access::object_traits_impl< ::withdrawal, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::withdrawal, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[3UL] = false;

    // _from_acct
    //
    t[4UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::bind (b + n, i, sk);
    n += 3UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _from_acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._from_acct_value;
    b[n].is_null = &i._from_acct_null;
    n++;
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::withdrawal, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._from_acct_value,
          is_null,
          id);
        i._from_acct_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._from_acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._from_acct_value,
          i._from_acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::persist_statement[] =
  "INSERT INTO \"withdrawal\" "
  "(\"amount\", "
  "\"datetime\", "
  "\"description\", "
  "\"id\", "
  "\"from_acct\") "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::find_statement[] =
  "SELECT "
  "\"withdrawal\".\"amount\", "
  "\"withdrawal\".\"datetime\", "
  "\"withdrawal\".\"description\", "
  "\"withdrawal\".\"id\", "
  "\"withdrawal\".\"from_acct\" "
  "FROM \"withdrawal\" "
  "WHERE \"withdrawal\".\"id\"=?";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::update_statement[] =
  "UPDATE \"withdrawal\" "
  "SET "
  "\"amount\"=?, "
  "\"datetime\"=?, "
  "\"description\"=?, "
  "\"from_acct\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::erase_statement[] =
  "DELETE FROM \"withdrawal\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"withdrawal\".\"amount\",\n"
  "\"withdrawal\".\"datetime\",\n"
  "\"withdrawal\".\"description\",\n"
  "\"withdrawal\".\"id\",\n"
  "\"withdrawal\".\"from_acct\"\n"
  "FROM \"withdrawal\"\n"
  "LEFT JOIN \"account\" AS \"from_acct\" ON \"from_acct\".\"acct_num\"=\"withdrawal\".\"from_acct\"";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"withdrawal\"";

  const char access::object_traits_impl< ::withdrawal, id_sqlite >::table_name[] =
  "\"withdrawal\"";

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::withdrawal, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::withdrawal, id_sqlite >::pointer_type
  access::object_traits_impl< ::withdrawal, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::withdrawal, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::withdrawal, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::withdrawal, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::withdrawal, id_sqlite >::object_type >
  access::object_traits_impl< ::withdrawal, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::withdrawal, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // deposit
  //

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::deposit, id_sqlite >::to_acct_tag>::
  table_name[] = "\"to_acct\"";

  struct access::object_traits_impl< ::deposit, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::deposit, id_sqlite >::id_type
  access::object_traits_impl< ::deposit, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::deposit, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[3UL] = false;

    // _to_acct
    //
    t[4UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::bind (b + n, i, sk);
    n += 3UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _to_acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._to_acct_value;
    b[n].is_null = &i._to_acct_null;
    n++;
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::deposit, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    // _to_acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._to_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._to_acct_value,
          is_null,
          id);
        i._to_acct_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _to_acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._to_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._to_acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._to_acct_value,
          i._to_acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::deposit, id_sqlite >::persist_statement[] =
  "INSERT INTO \"deposit\" "
  "(\"amount\", "
  "\"datetime\", "
  "\"description\", "
  "\"id\", "
  "\"to_acct\") "
  "VALUES "
  "(?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::deposit, id_sqlite >::find_statement[] =
  "SELECT "
  "\"deposit\".\"amount\", "
  "\"deposit\".\"datetime\", "
  "\"deposit\".\"description\", "
  "\"deposit\".\"id\", "
  "\"deposit\".\"to_acct\" "
  "FROM \"deposit\" "
  "WHERE \"deposit\".\"id\"=?";

  const char access::object_traits_impl< ::deposit, id_sqlite >::update_statement[] =
  "UPDATE \"deposit\" "
  "SET "
  "\"amount\"=?, "
  "\"datetime\"=?, "
  "\"description\"=?, "
  "\"to_acct\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::deposit, id_sqlite >::erase_statement[] =
  "DELETE FROM \"deposit\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::deposit, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"deposit\".\"amount\",\n"
  "\"deposit\".\"datetime\",\n"
  "\"deposit\".\"description\",\n"
  "\"deposit\".\"id\",\n"
  "\"deposit\".\"to_acct\"\n"
  "FROM \"deposit\"\n"
  "LEFT JOIN \"account\" AS \"to_acct\" ON \"to_acct\".\"acct_num\"=\"deposit\".\"to_acct\"";

  const char access::object_traits_impl< ::deposit, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"deposit\"";

  const char access::object_traits_impl< ::deposit, id_sqlite >::table_name[] =
  "\"deposit\"";

  void access::object_traits_impl< ::deposit, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::deposit, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::deposit, id_sqlite >::pointer_type
  access::object_traits_impl< ::deposit, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::deposit, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::deposit, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::deposit, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::deposit, id_sqlite >::object_type >
  access::object_traits_impl< ::deposit, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::deposit, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }

  // transfer
  //

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::transfer, id_sqlite >::to_acct_tag>::
  table_name[] = "\"to_acct\"";

  const char alias_traits<  ::account,
    id_sqlite,
    access::object_traits_impl< ::transfer, id_sqlite >::from_acct_tag>::
  table_name[] = "\"from_acct\"";

  struct access::object_traits_impl< ::transfer, id_sqlite >::extra_statement_cache_type
  {
    extra_statement_cache_type (
      sqlite::connection&,
      image_type&,
      id_image_type&,
      sqlite::binding&,
      sqlite::binding&)
    {
    }
  };

  access::object_traits_impl< ::transfer, id_sqlite >::id_type
  access::object_traits_impl< ::transfer, id_sqlite >::
  id (const image_type& i)
  {
    sqlite::database* db (0);
    ODB_POTENTIALLY_UNUSED (db);

    id_type id;
    {
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        id,
        i._id_value,
        i._id_null);
    }

    return id;
  }

  bool access::object_traits_impl< ::transfer, id_sqlite >::
  grow (image_type& i,
        bool* t)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (t);

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::grow (
          i, t + 0UL))
      grew = true;

    // _id
    //
    t[3UL] = false;

    // _to_acct
    //
    t[4UL] = false;

    // _from_acct
    //
    t[5UL] = false;

    return grew;
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  bind (sqlite::bind* b,
        image_type& i,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    std::size_t n (0);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::bind (b + n, i, sk);
    n += 3UL;

    // _id
    //
    if (sk != statement_update)
    {
      b[n].type = sqlite::bind::integer;
      b[n].buffer = &i._id_value;
      b[n].is_null = &i._id_null;
      n++;
    }

    // _to_acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._to_acct_value;
    b[n].is_null = &i._to_acct_null;
    n++;

    // _from_acct
    //
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i._from_acct_value;
    b[n].is_null = &i._from_acct_null;
    n++;
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  bind (sqlite::bind* b, id_image_type& i)
  {
    std::size_t n (0);
    b[n].type = sqlite::bind::integer;
    b[n].buffer = &i.id_value;
    b[n].is_null = &i.id_null;
  }

  bool access::object_traits_impl< ::transfer, id_sqlite >::
  init (image_type& i,
        const object_type& o,
        sqlite::statement_kind sk)
  {
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (sk);

    using namespace sqlite;

    bool grew (false);

    // transaction base
    //
    if (object_traits_impl< ::transaction, id_sqlite >::init (i, o, sk))
      grew = true;

    // _id
    //
    if (sk == statement_insert)
    {
      unsigned int const& v =
        o._id;

      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i._id_value,
        is_null,
        v);
      i._id_null = is_null;
    }

    // _to_acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._to_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._to_acct_value,
          is_null,
          id);
        i._to_acct_null = is_null;
      }
      else
        throw null_pointer ();
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account > const& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      bool is_null (ptr_traits::null_ptr (v));
      if (!is_null)
      {
        const obj_traits::id_type& id (
          obj_traits::id (ptr_traits::get_ref (v)));

        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_image (
          i._from_acct_value,
          is_null,
          id);
        i._from_acct_null = is_null;
      }
      else
        throw null_pointer ();
    }

    return grew;
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  init (object_type& o,
        const image_type& i,
        database* db)
  {
    ODB_POTENTIALLY_UNUSED (o);
    ODB_POTENTIALLY_UNUSED (i);
    ODB_POTENTIALLY_UNUSED (db);

    // transaction base
    //
    object_traits_impl< ::transaction, id_sqlite >::init (o, i, db);

    // _id
    //
    {
      unsigned int& v =
        o._id;

      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_value (
        v,
        i._id_value,
        i._id_null);
    }

    // _to_acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._to_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._to_acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._to_acct_value,
          i._to_acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }

    // _from_acct
    //
    {
      ::std::shared_ptr< ::account >& v =
        o._from_acct;

      typedef object_traits< ::account > obj_traits;
      typedef odb::pointer_traits< ::std::shared_ptr< ::account > > ptr_traits;

      if (i._from_acct_null)
        v = ptr_traits::pointer_type ();
      else
      {
        obj_traits::id_type id;
        sqlite::value_traits<
            obj_traits::id_type,
            sqlite::id_integer >::set_value (
          id,
          i._from_acct_value,
          i._from_acct_null);

        // If a compiler error points to the line below, then
        // it most likely means that a pointer used in a member
        // cannot be initialized from an object pointer.
        //
        v = ptr_traits::pointer_type (
          static_cast<sqlite::database*> (db)->load<
            obj_traits::object_type > (id));
      }
    }
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  init (id_image_type& i, const id_type& id)
  {
    {
      bool is_null (false);
      sqlite::value_traits<
          unsigned int,
          sqlite::id_integer >::set_image (
        i.id_value,
        is_null,
        id);
      i.id_null = is_null;
    }
  }

  const char access::object_traits_impl< ::transfer, id_sqlite >::persist_statement[] =
  "INSERT INTO \"transfer\" "
  "(\"amount\", "
  "\"datetime\", "
  "\"description\", "
  "\"id\", "
  "\"to_acct\", "
  "\"from_acct\") "
  "VALUES "
  "(?, ?, ?, ?, ?, ?)";

  const char access::object_traits_impl< ::transfer, id_sqlite >::find_statement[] =
  "SELECT "
  "\"transfer\".\"amount\", "
  "\"transfer\".\"datetime\", "
  "\"transfer\".\"description\", "
  "\"transfer\".\"id\", "
  "\"transfer\".\"to_acct\", "
  "\"transfer\".\"from_acct\" "
  "FROM \"transfer\" "
  "WHERE \"transfer\".\"id\"=?";

  const char access::object_traits_impl< ::transfer, id_sqlite >::update_statement[] =
  "UPDATE \"transfer\" "
  "SET "
  "\"amount\"=?, "
  "\"datetime\"=?, "
  "\"description\"=?, "
  "\"to_acct\"=?, "
  "\"from_acct\"=? "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::transfer, id_sqlite >::erase_statement[] =
  "DELETE FROM \"transfer\" "
  "WHERE \"id\"=?";

  const char access::object_traits_impl< ::transfer, id_sqlite >::query_statement[] =
  "SELECT\n"
  "\"transfer\".\"amount\",\n"
  "\"transfer\".\"datetime\",\n"
  "\"transfer\".\"description\",\n"
  "\"transfer\".\"id\",\n"
  "\"transfer\".\"to_acct\",\n"
  "\"transfer\".\"from_acct\"\n"
  "FROM \"transfer\"\n"
  "LEFT JOIN \"account\" AS \"to_acct\" ON \"to_acct\".\"acct_num\"=\"transfer\".\"to_acct\"\n"
  "LEFT JOIN \"account\" AS \"from_acct\" ON \"from_acct\".\"acct_num\"=\"transfer\".\"from_acct\"";

  const char access::object_traits_impl< ::transfer, id_sqlite >::erase_query_statement[] =
  "DELETE FROM \"transfer\"";

  const char access::object_traits_impl< ::transfer, id_sqlite >::table_name[] =
  "\"transfer\"";

  void access::object_traits_impl< ::transfer, id_sqlite >::
  persist (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    callback (db,
              obj,
              callback_event::pre_persist);

    image_type& im (sts.image ());
    binding& imb (sts.insert_image_binding ());

    if (init (im, obj, statement_insert))
      im.version++;

    if (im.version != sts.insert_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_insert);
      sts.insert_image_version (im.version);
      imb.version++;
    }

    insert_statement& st (sts.persist_statement ());
    if (!st.execute ())
      throw object_already_persistent ();

    callback (db,
              obj,
              callback_event::post_persist);
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  update (database& db, const object_type& obj)
  {
    ODB_POTENTIALLY_UNUSED (db);

    using namespace sqlite;
    using sqlite::update_statement;

    callback (db, obj, callback_event::pre_update);

    sqlite::transaction& tr (sqlite::transaction::current ());
    sqlite::connection& conn (tr.connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    const id_type& id (
      obj._id);
    id_image_type& idi (sts.id_image ());
    init (idi, id);

    image_type& im (sts.image ());
    if (init (im, obj, statement_update))
      im.version++;

    bool u (false);
    binding& imb (sts.update_image_binding ());
    if (im.version != sts.update_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_update);
      sts.update_image_version (im.version);
      imb.version++;
      u = true;
    }

    binding& idb (sts.id_image_binding ());
    if (idi.version != sts.update_id_image_version () ||
        idb.version == 0)
    {
      if (idi.version != sts.id_image_version () ||
          idb.version == 0)
      {
        bind (idb.bind, idi);
        sts.id_image_version (idi.version);
        idb.version++;
      }

      sts.update_id_image_version (idi.version);

      if (!u)
        imb.version++;
    }

    update_statement& st (sts.update_statement ());
    if (st.execute () == 0)
      throw object_not_persistent ();

    callback (db, obj, callback_event::post_update);
    pointer_cache_traits::update (db, obj);
  }

  void access::object_traits_impl< ::transfer, id_sqlite >::
  erase (database& db, const id_type& id)
  {
    using namespace sqlite;

    ODB_POTENTIALLY_UNUSED (db);

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    id_image_type& i (sts.id_image ());
    init (i, id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    if (sts.erase_statement ().execute () != 1)
      throw object_not_persistent ();

    pointer_cache_traits::erase (db, id);
  }

  access::object_traits_impl< ::transfer, id_sqlite >::pointer_type
  access::object_traits_impl< ::transfer, id_sqlite >::
  find (database& db, const id_type& id)
  {
    using namespace sqlite;

    {
      pointer_type p (pointer_cache_traits::find (db, id));

      if (!pointer_traits::null_ptr (p))
        return p;
    }

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (l.locked ())
    {
      if (!find_ (sts, &id))
        return pointer_type ();
    }

    pointer_type p (
      access::object_factory<object_type, pointer_type>::create ());
    pointer_traits::guard pg (p);

    pointer_cache_traits::insert_guard ig (
      pointer_cache_traits::insert (db, id, p));

    object_type& obj (pointer_traits::get_ref (p));

    if (l.locked ())
    {
      select_statement& st (sts.find_statement ());
      ODB_POTENTIALLY_UNUSED (st);

      callback (db, obj, callback_event::pre_load);
      init (obj, sts.image (), &db);
      load_ (sts, obj, false);
      sts.load_delayed (0);
      l.unlock ();
      callback (db, obj, callback_event::post_load);
      pointer_cache_traits::load (ig.position ());
    }
    else
      sts.delay_load (id, obj, ig.position ());

    ig.release ();
    pg.release ();
    return p;
  }

  bool access::object_traits_impl< ::transfer, id_sqlite >::
  find (database& db, const id_type& id, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    reference_cache_traits::position_type pos (
      reference_cache_traits::insert (db, id, obj));
    reference_cache_traits::insert_guard ig (pos);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, false);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    reference_cache_traits::load (pos);
    ig.release ();
    return true;
  }

  bool access::object_traits_impl< ::transfer, id_sqlite >::
  reload (database& db, object_type& obj)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());
    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    statements_type::auto_lock l (sts);

    const id_type& id  (
      obj._id);

    if (!find_ (sts, &id))
      return false;

    select_statement& st (sts.find_statement ());
    ODB_POTENTIALLY_UNUSED (st);

    callback (db, obj, callback_event::pre_load);
    init (obj, sts.image (), &db);
    load_ (sts, obj, true);
    sts.load_delayed (0);
    l.unlock ();
    callback (db, obj, callback_event::post_load);
    return true;
  }

  bool access::object_traits_impl< ::transfer, id_sqlite >::
  find_ (statements_type& sts,
         const id_type* id)
  {
    using namespace sqlite;

    id_image_type& i (sts.id_image ());
    init (i, *id);

    binding& idb (sts.id_image_binding ());
    if (i.version != sts.id_image_version () || idb.version == 0)
    {
      bind (idb.bind, i);
      sts.id_image_version (i.version);
      idb.version++;
    }

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    select_statement& st (sts.find_statement ());

    st.execute ();
    auto_result ar (st);
    select_statement::result r (st.fetch ());

    if (r == select_statement::truncated)
    {
      if (grow (im, sts.select_image_truncated ()))
        im.version++;

      if (im.version != sts.select_image_version ())
      {
        bind (imb.bind, im, statement_select);
        sts.select_image_version (im.version);
        imb.version++;
        st.refetch ();
      }
    }

    return r != select_statement::no_data;
  }

  result< access::object_traits_impl< ::transfer, id_sqlite >::object_type >
  access::object_traits_impl< ::transfer, id_sqlite >::
  query (database&, const query_base_type& q)
  {
    using namespace sqlite;
    using odb::details::shared;
    using odb::details::shared_ptr;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    statements_type& sts (
      conn.statement_cache ().find_object<object_type> ());

    image_type& im (sts.image ());
    binding& imb (sts.select_image_binding ());

    if (im.version != sts.select_image_version () ||
        imb.version == 0)
    {
      bind (imb.bind, im, statement_select);
      sts.select_image_version (im.version);
      imb.version++;
    }

    std::string text (query_statement);
    if (!q.empty ())
    {
      text += "\n";
      text += q.clause ();
    }

    q.init_parameters ();
    shared_ptr<select_statement> st (
      new (shared) select_statement (
        conn,
        text,
        true,
        true,
        q.parameters_binding (),
        imb));

    st->execute ();

    shared_ptr< odb::object_result_impl<object_type> > r (
      new (shared) sqlite::object_result_impl<object_type> (
        q, st, sts, 0));

    return result<object_type> (r);
  }

  unsigned long long access::object_traits_impl< ::transfer, id_sqlite >::
  erase_query (database&, const query_base_type& q)
  {
    using namespace sqlite;

    sqlite::connection& conn (
      sqlite::transaction::current ().connection ());

    std::string text (erase_query_statement);
    if (!q.empty ())
    {
      text += ' ';
      text += q.clause ();
    }

    q.init_parameters ();
    delete_statement st (
      conn,
      text,
      q.parameters_binding ());

    return st.execute ();
  }
}

namespace odb
{
  static bool
  create_schema (database& db, unsigned short pass, bool drop)
  {
    ODB_POTENTIALLY_UNUSED (db);
    ODB_POTENTIALLY_UNUSED (pass);
    ODB_POTENTIALLY_UNUSED (drop);

    if (drop)
    {
      switch (pass)
      {
        case 1:
        {
          return true;
        }
        case 2:
        {
          db.execute ("DROP TABLE IF EXISTS \"transfer\"");
          db.execute ("DROP TABLE IF EXISTS \"deposit\"");
          db.execute ("DROP TABLE IF EXISTS \"withdrawal\"");
          return false;
        }
      }
    }
    else
    {
      switch (pass)
      {
        case 1:
        {
          db.execute ("CREATE TABLE \"withdrawal\" (\n"
                      "  \"amount\" REAL NULL DEFAULT 0,\n"
                      "  \"datetime\" INTEGER NOT NULL default current_timestamp,\n"
                      "  \"description\" TEXT NOT NULL DEFAULT '',\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"from_acct\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"from_acct_fk\"\n"
                      "    FOREIGN KEY (\"from_acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE TABLE \"deposit\" (\n"
                      "  \"amount\" REAL NULL DEFAULT 0,\n"
                      "  \"datetime\" INTEGER NOT NULL default current_timestamp,\n"
                      "  \"description\" TEXT NOT NULL DEFAULT '',\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"to_acct\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"to_acct_fk\"\n"
                      "    FOREIGN KEY (\"to_acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          db.execute ("CREATE TABLE \"transfer\" (\n"
                      "  \"amount\" REAL NULL DEFAULT 0,\n"
                      "  \"datetime\" INTEGER NOT NULL default current_timestamp,\n"
                      "  \"description\" TEXT NOT NULL DEFAULT '',\n"
                      "  \"id\" INTEGER NOT NULL PRIMARY KEY,\n"
                      "  \"to_acct\" INTEGER NOT NULL,\n"
                      "  \"from_acct\" INTEGER NOT NULL,\n"
                      "  CONSTRAINT \"to_acct_fk\"\n"
                      "    FOREIGN KEY (\"to_acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED,\n"
                      "  CONSTRAINT \"from_acct_fk\"\n"
                      "    FOREIGN KEY (\"from_acct\")\n"
                      "    REFERENCES \"account\" (\"acct_num\")\n"
                      "    DEFERRABLE INITIALLY DEFERRED)");
          return false;
        }
      }
    }

    return false;
  }

  static const schema_catalog_create_entry
  create_schema_entry_ (
    id_sqlite,
    "",
    &create_schema);
}

#include <odb/post.hxx>
